apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: aws-exam
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_WITH_LONG_RANDOM_SECRET"
  MONGODB_URI: "mongodb+srv://USERNAME:PASSWORD@CLUSTER.mongodb.net/?retryWrites=true&w=majority"
