apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-data
  namespace: aws-exam
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # k3s's built-in default provisioner
  resources:
    requests:
      storage: 1Gi
